version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: governanceDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: governance
      POSTGRES_DB: governance
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    image: yukilabs/governance-backend
    build:
      dockerfile: backend.Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 8000
      CLIENT_ORIGIN: http://localhost:3000
      DATABASE_URL: postgresql://postgres:governance@localhost:5432/governance
      DYNAMIC_PUBLIC_KEY: |
        -----BEGIN PUBLIC KEY-----
        MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA3dNuD1XQP+7JDjrdNElu
        aFyhc8HNMnOuAWTekoCmZEyrc4QVH4EUw3IXZsKvoJ8j5405jGQ9s9xSH7AyZ/q7
        0hkW7BMRwDkPPNVctXNosrTTmHERgQEcSqiiEL0X5KIAgCj87AcBrrSZMwHXio+H
        vKHaXfVu/tUllBKipYtnhwl/lXnMBbRQzwruajASdGodPyhuy67H44DEvXXalVeZ
        2Pglm4ao6SoVgRlLHQtbrK+LLZnqV4s0nMuXIbL1/yE3SPaevqvTVwi3ajExVS+T
        FydCkSkpvGn7EeQ8twJ8aQ3LkvQgf8chKD5hNLajkPFinDxexicMEArV9E6sRRSj
        jATdTqyV6aXZo437Mc6fgAxBJ1oqtUedKuucO6XXenYgnj4RTp4v0sVsBHd/aJDU
        heqEitHm25hcC5pV9pMbPLcqbdghhP2z4OU4TN3tbVP0bC9Zc0H7b3QZr/4/IwsP
        p7RZcWe4ZBY/7UDaCAln7Vq9BANFntMIC8IsSQ15BWr5CRhcAItYt8A8DDyBv3hx
        tde5uahi/HSdcr/K5sw4ZcN8tW+VVLSgUUUd9REGVVWQBWtTHhyexdq4iRs/1X4o
        WfVrZv4VF59Pj7BLY3etIBKOvM9QwjTKX/3OtiGfv1tWe2rDuwVt1tSOFH7kDb8O
        zEWTPjltmicWkpyQKcRaAx0CAwEAAQ==
        -----END PUBLIC KEY-----
    ports:
      - 8000:8000

  frontend:
    image: yukilabs/governance-frontend
    build:
      dockerfile: frontend.Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NODE_PATH: /runtime/node_modules
      VITE_APP_DYNAMIC_ID: a99f1241-3620-4df1-9673-96b3a3684cdf
      VITE_APP_TRPC_URL: http://localhost:8000/trpc
      VITE_APP_IFRAMELY_ID: cd5533d79f906cb13440b5aee09e99af
      VITE_APP_SNAPSHOT_URL: https://hub.snapshot.org
      VITE_APP_SNAPSHOT_SPACE: robwalsh.eth
      VITE_APP_SNAPSHOT_CHAIN_ID: 1
      VITE_APP_GOOGLE_TAG_ID: G-WY42TERK5P
      VITE_APP_DELEGATION_REGISTRY: 0x469788fE6E9E9681C6ebF3bF78e7Fd26Fc015446
      VITE_APP_DELEGATION_TOKEN: 0x65aFADD39029741B3b8f0756952C74678c9cEC93
      VITE_APP_DELEGATION_SYMBOL: USDC
      VITE_APP_DELEGATION_CHAIN_ID: 5

    ports:
      - 3000:3000
