import {
  BoldIcon,
  ItalicIcon,
  UnderlineIcon,
  Heading2Icon,
  NumberedListIcon,
  BulletedListIcon,
  ImageIcon,
  LinkIcon,
} from "./ToolbarIcons";
import {
  ProposalsIcon,
  HomeIcon,
  SnipsIcon,
  BuildersIcon,
  DelegatesIcon,
  FeedbackIcon,
  LearnIcon,
  SecurityIcon,
  SettingsIcon,
  SupportIcon,
  ArrowLeftIcon,
  CommentIcon,
  NoDelegatesIcon,
  NoPostsIcon,
  NoSnipsIcon,
  PencilIcon,
  TrashIcon,
  SuccessIcon,
  TrashWarningIcon,
  VoteIcon,
  WarningIcon,
  ExternalLinkIcon,
  VoteAbstainIcon,
  VoteAgainstIcon,
  VoteForIcon,
  StarknetCommunityIcon,
  StarknetIcon,
  CopyIcon,
  FiltersIcon,
  DiscordIcon,
  SearchIcon,
  ShareIcon,
  ProfileIcon,
  HamburgerIcon,
  PlusIcon,
  SortIcon,
  EllipsisIcon,
  InfoIcon,
  XIcon,
  SignatureIcon,
  ImageWarningIcon,
  WalletIcon,
} from "./UiIcons";
// import {
//   HiOutlineCodeBracketSquare,
//   HiOutlineLockClosed,
//   HiOutlineDocumentText,
//   HiOutlineUserCircle,
//   HiOutlineAcademicCap,
//   HiOutlineQuestionMarkCircle,
//   HiOutlineChatBubbleLeftRight,
//   HiOutlineChatBubbleLeftEllipsis,
//   HiAdjustmentsHorizontal,
//   HiEllipsisHorizontal,
//   HiTrash,
//   HiOutlinePencil,
//   HiOutlineTrash,
//   HiXMark,
//   HiOutlineArrowUpRight,
// } from "react-icons/hi2";
// import { MdOutlineHowToVote, MdOutlineAssignment } from "react-icons/md";
// import { GiHamburgerMenu } from "react-icons/gi";
export {
  // HiOutlineCodeBracketSquare,
  // HiOutlineLockClosed,
  // HiOutlineDocumentText,
  // HiOutlineUserCircle,
  // HiOutlineAcademicCap,
  // HiOutlineQuestionMarkCircle,
  // HiOutlineChatBubbleLeftRight,
  // HiOutlineChatBubbleLeftEllipsis,
  // MdOutlineHowToVote,
  // MdOutlineAssignment,
  // HiAdjustmentsHorizontal,
  // HiEllipsisHorizontal,
  BoldIcon,
  ItalicIcon,
  UnderlineIcon,
  Heading2Icon,
  NumberedListIcon,
  BulletedListIcon,
  ImageIcon,
  LinkIcon,
  ProposalsIcon,
  HomeIcon,
  SnipsIcon,
  BuildersIcon,
  DelegatesIcon,
  FeedbackIcon,
  LearnIcon,
  SecurityIcon,
  SettingsIcon,
  SupportIcon,
  ArrowLeftIcon,
  CommentIcon,
  NoDelegatesIcon,
  NoPostsIcon,
  NoSnipsIcon,
  PencilIcon,
  TrashIcon,
  FiltersIcon,
  SuccessIcon,
  TrashWarningIcon,
  VoteIcon,
  WarningIcon,
  ExternalLinkIcon,
  VoteAbstainIcon,
  VoteAgainstIcon,
  VoteForIcon,
  StarknetCommunityIcon,
  StarknetIcon,
  DiscordIcon,
  ShareIcon,
  CopyIcon,
  SearchIcon,
  ProfileIcon,
  HamburgerIcon,
  PlusIcon,
  SortIcon,
  EllipsisIcon,
  InfoIcon,
  XIcon,
  SignatureIcon,
  ImageWarningIcon,
  WalletIcon,
};
