import {
  BoldIcon,
  ItalicIcon,
  UnderlineIcon,
  Heading2Icon,
  NumberedListIcon,
  BulletedListIcon,
  ImageIcon,
  LinkIcon,
} from "./ToolbarIcons";
import {
  HiOutlineCodeBracketSquare,
  HiOutlineLockClosed,
  HiOutlineDocumentText,
  HiOutlineUserCircle,
  HiOutlineAcademicCap,
  HiOutlineQuestionMarkCircle,
  HiOutlineChatBubbleLeftRight,
  HiOutlineChatBubbleLeftEllipsis,
  HiAdjustmentsHorizontal,
  HiEllipsisHorizontal,
  HiTrash,
} from "react-icons/hi2";
import { MdOutlineHowToVote, MdOutlineAssignment } from "react-icons/md";

export {
  HiOutlineCodeBracketSquare,
  HiOutlineLockClosed,
  HiOutlineDocumentText,
  HiOutlineUserCircle,
  HiOutlineAcademicCap,
  HiOutlineQuestionMarkCircle,
  HiOutlineChatBubbleLeftRight,
  HiOutlineChatBubbleLeftEllipsis,
  MdOutlineHowToVote,
  MdOutlineAssignment,
  HiAdjustmentsHorizontal,
  HiEllipsisHorizontal,
  BoldIcon,
  ItalicIcon,
  UnderlineIcon,
  Heading2Icon,
  NumberedListIcon,
  BulletedListIcon,
  ImageIcon,
  LinkIcon,
  HiTrash,
};
