version: "3.9"

services:
  backend:
    image: '${image}'
    restart: unless-stopped
    ports:
      - ${external_port}:${port}
    environment:
      PORT: ${port}
      DATABASE_URL: ${database_url}
      DYNAMIC_PUBLIC_KEY: ${dynamic_public_key}
      CLIENT_ORIGIN: ${client_url}
    networks:
      yuki:

networks:
  yuki:
    external: true
    name: 'yuki-${environment}'

