name: back deployment (prod)

on:
  push:
    tags:
      - 'v*'
    paths:
      - 'workspaces/backend/**'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: europe-west9-docker.pkg.dev/gov-hub-prod/api/prod
          flavor: latest=false
          tags: |
            type=ref,event=tag

      - uses: 'google-github-actions/auth@v2'
        id: auth
        with:
          token_format: access_token
          project_id: 'gov-hub-prod'
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS_PROD }}'

      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: europe-west9-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: backend.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            "certificate=${{ secrets.CERTIFICATE }}"

  Deploy-production:
    needs: Build
    runs-on: ubuntu-latest
    env:
      image: ${{ needs.Build.outputs.image }}
    environment:
      name: production-backend
      url: https://api.yuki-labs.dev
    steps:
      - uses: 'google-github-actions/auth@v2'
        id: auth
        with:
          token_format: access_token
          project_id: 'gov-hub-prod'
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS_PROD }}'

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: api
          image: ${{ env.image }}
          region: europe-west9
