name: "Retention policy"
on:
  push:
  workflow_dispatch:
  #schedule:
  #  - cron: "0 0 * * *"

jobs:
  frontend_cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: cleanup frontend images
        run: |
          TAGS=$(doctl registry repository lt frontend | tail -n +5 | awk '{print $1}')
          [[ -n $TAGS ]] && doctl registry repository dt frontend $TAGS --force
          echo Tags removed: $TAGS

  backend_cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: cleanup backend images
        run: |
          TAGS=$(doctl registry repository lt backend | tail -n +5 | awk '{print $1}')
          [[ -n $TAGS ]] && doctl registry repository dt backend $TAGS --force
          echo Tags removed: $TAGS
